// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH inserted_feed_follow AS (
	INSERT INTO feed_follows (id, user_id, feed_id, updated_at, created_at)
	VALUES($1, $2, $3, $4, $5)
	RETURNING id, created_at, updated_at, user_id, feed_id
)
SELECT 
	iif.id, iif.created_at, iif.updated_at, iif.user_id, iif.feed_id, 
	f.name AS feed_name,
	u.name AS user_name 
	FROM inserted_feed_follow AS iif
	JOIN users AS u ON u.id = iif.user_id
	JOIN feeds AS f ON f.id = iif.feed_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	UpdatedAt time.Time
	CreatedAt time.Time
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	FeedName  string
	UserName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.UserID,
		arg.FeedID,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}

const findFeedByUrl = `-- name: FindFeedByUrl :one
SELECT id, name, url FROM feeds WHERE url = $1
`

type FindFeedByUrlRow struct {
	ID   uuid.UUID
	Name string
	Url  string
}

func (q *Queries) FindFeedByUrl(ctx context.Context, url string) (FindFeedByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, findFeedByUrl, url)
	var i FindFeedByUrlRow
	err := row.Scan(&i.ID, &i.Name, &i.Url)
	return i, err
}
