-- +goose Up
CREATE TABLE users(
	id UUID NOT NULL PRIMARY KEY, 
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), 
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	name TEXT UNIQUE NOT NULL
);
-- +goose Down
DROP TABLE users;
